ifneq ($(wildcard /Applications/GowinIDE.app/Contents/Resources/Gowin_EDA/IDE/bin),)
    $(info Using Gowin IDE Toolchain on Mac)
	GW_SH = /Applications/GowinIDE.app/Contents/Resources/Gowin_EDA/IDE/bin/gw_sh
else
    $(info Using Gowin IDE Toolchain on Linux)
	GW_SH = /opt/gowin/bin
endif

